finger_names:
- thumb
- index
- middle
- ring
- little
hand_marker_names:
- hand_top
- hand_left
- hand_right
finger_marker_names:
    thumb:
    - thumb_tip
    - thumb_middle
    index:
    - index_tip
    - index_middle
    middle:
    - middle_tip
    - middle_middle
    ring:
    - ring_tip
    - ring_middle
    little:
    - little_tip
    - little_middle
additional_markers:
- protector_left
- protector_right
- protector_top
scale: 1.0
